version: 0.2

phases:
  install:
    commands:
        - sudo yum update -y
        - sudo yum remove python3 -y
        - sudo yum install python3 -y
        - sudo yum install python3-pip
        - pip3 -V
        - python3 -m pip3 install Flask
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - python test_app.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - web.py
    - appspec.yml
    - templates/layout.html
    - templates/test.html
    - scripts/mkdir.sh
    - scripts/start_flask.sh
    - scripts/stop_flask1.sh
    - scripts/stop_flask.py
