version: 0.2

phases:
  install:
    commands:
        - curl -O https://bootstrap.pypa.io/get-pip.py
        - sudo apt install python3
        - python3 --version
        - python --version
        - python3 get-pip.py --user
        - pip --version
        - pip3 --version
        - python3 -m pip install Flask
        - python -m pip install Flask
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - python test_app.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - web.py
    - appspec.yml
    - templates/layout.html
    - templates/test.html
    - scripts/mkdir.sh
    - scripts/start_flask.sh
    - scripts/stop_flask1.sh
    - scripts/stop_flask.py
